# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1_startup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startup_window(object):
    def setupUi(self, startup_window):
        startup_window.setObjectName("startup_window")
        startup_window.resize(1280, 800)
        startup_window.setMinimumSize(QtCore.QSize(1280, 800))
        startup_window.setMaximumSize(QtCore.QSize(1280, 800))
        self.centralwidget = QtWidgets.QWidget(startup_window)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(430, 50, 411, 221))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("img/Logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 1024))
        self.background.setMinimumSize(QtCore.QSize(1280, 1024))
        self.background.setMaximumSize(QtCore.QSize(1280, 1024))
        self.background.setAutoFillBackground(True)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background_fillter = QtWidgets.QLabel(self.centralwidget)
        self.background_fillter.setGeometry(QtCore.QRect(0, 0, 1280, 1024))
        self.background_fillter.setMinimumSize(QtCore.QSize(1280, 1024))
        self.background_fillter.setMaximumSize(QtCore.QSize(1280, 1024))
        self.background_fillter.setSizeIncrement(QtCore.QSize(0, 0))
        self.background_fillter.setBaseSize(QtCore.QSize(0, 0))
        self.background_fillter.setStyleSheet("QLabel{\n"
"    background: rgb(8, 78, 142,60%);\n"
"}")
        self.background_fillter.setText("")
        self.background_fillter.setObjectName("background_fillter")
        self.admissions_consultancy = QtWidgets.QPushButton(self.centralwidget)
        self.admissions_consultancy.setGeometry(QtCore.QRect(530, 440, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.admissions_consultancy.setFont(font)
        self.admissions_consultancy.setTabletTracking(False)
        self.admissions_consultancy.setAutoFillBackground(False)
        self.admissions_consultancy.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 20px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 20px;\n"
"    border: 7px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.admissions_consultancy.setObjectName("admissions_consultancy")
        self.tittle_app = QtWidgets.QPushButton(self.centralwidget)
        self.tittle_app.setGeometry(QtCore.QRect(270, 310, 711, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tittle_app.sizePolicy().hasHeightForWidth())
        self.tittle_app.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tittle_app.setFont(font)
        self.tittle_app.setTabletTracking(False)
        self.tittle_app.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"Tahoma\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 20pt \"Tahoma\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.tittle_app.setObjectName("tittle_app")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(420, 670, 281, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_input.sizePolicy().hasHeightForWidth())
        self.password_input.setSizePolicy(sizePolicy)
        self.password_input.setStyleSheet("QLineEdit{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 14pt \"Tahoma\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(420, 600, 431, 51))
        self.username_input.setStyleSheet("QLineEdit{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 14pt \"Tahoma\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.username_input.setText("")
        self.username_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_input.setObjectName("username_input")
        self.title_formadmin = QtWidgets.QLabel(self.centralwidget)
        self.title_formadmin.setGeometry(QtCore.QRect(460, 520, 361, 71))
        self.title_formadmin.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"text-align: center;\n"
"vertical-align: middle;")
        self.title_formadmin.setAlignment(QtCore.Qt.AlignCenter)
        self.title_formadmin.setObjectName("title_formadmin")
        self.loggin_admin = QtWidgets.QPushButton(self.centralwidget)
        self.loggin_admin.setGeometry(QtCore.QRect(720, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loggin_admin.sizePolicy().hasHeightForWidth())
        self.loggin_admin.setSizePolicy(sizePolicy)
        self.loggin_admin.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.loggin_admin.setAutoRepeatDelay(300)
        self.loggin_admin.setAutoDefault(True)
        self.loggin_admin.setFlat(False)
        self.loggin_admin.setObjectName("loggin_admin")
        self.admin_form = QtWidgets.QLabel(self.centralwidget)
        self.admin_form.setEnabled(True)
        self.admin_form.setGeometry(QtCore.QRect(370, 520, 531, 221))
        self.admin_form.setMouseTracking(False)
        self.admin_form.setTabletTracking(False)
        self.admin_form.setFocusPolicy(QtCore.Qt.NoFocus)
        self.admin_form.setAcceptDrops(False)
        self.admin_form.setToolTip("")
        self.admin_form.setAccessibleName("")
        self.admin_form.setAutoFillBackground(False)
        self.admin_form.setStyleSheet("QLabel{\n"
"    gridline-color: rgb(32, 47, 255);\n"
"    background-color: rgb(8, 78, 142,90%);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.admin_form.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin_form.setText("")
        self.admin_form.setScaledContents(True)
        self.admin_form.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.admin_form.setObjectName("admin_form")
        self.note = QtWidgets.QLabel(self.centralwidget)
        self.note.setGeometry(QtCore.QRect(390, 750, 461, 31))
        self.note.setStyleSheet("font: 75 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.note.setText("")
        self.note.setAlignment(QtCore.Qt.AlignCenter)
        self.note.setObjectName("note")
        self.background.raise_()
        self.background_fillter.raise_()
        self.admin_form.raise_()
        self.Logo.raise_()
        self.admissions_consultancy.raise_()
        self.tittle_app.raise_()
        self.title_formadmin.raise_()
        self.username_input.raise_()
        self.password_input.raise_()
        self.loggin_admin.raise_()
        self.note.raise_()
        startup_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(startup_window)
        QtCore.QMetaObject.connectSlotsByName(startup_window)

    def retranslateUi(self, startup_window):
        _translate = QtCore.QCoreApplication.translate
        startup_window.setWindowTitle(_translate("startup_window", "PHẦN MỀM TƯ VẤN GIÁO DỤC"))
        self.admissions_consultancy.setText(_translate("startup_window", "Tư Vấn Giáo Vụ"))
        self.tittle_app.setText(_translate("startup_window", "Đại học Công Nghệ Sài Gòn"))
        self.password_input.setPlaceholderText(_translate("startup_window", "Mật Khẩu"))
        self.username_input.setPlaceholderText(_translate("startup_window", "Tài Khoản"))
        self.title_formadmin.setText(_translate("startup_window", "Đăng nhập quản trị viên"))
        self.loggin_admin.setText(_translate("startup_window", "Đăng Nhập"))
