# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window6_createadmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createadmin_window(object):
    def setupUi(self, createadmin_window):
        createadmin_window.setObjectName("createadmin_window")
        createadmin_window.resize(1280, 800)
        createadmin_window.setMinimumSize(QtCore.QSize(1280, 800))
        createadmin_window.setMaximumSize(QtCore.QSize(1280, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        createadmin_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(createadmin_window)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(90, 30, 231, 121))
        self.logo.setMinimumSize(QtCore.QSize(100, 100))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.tittle_window = QtWidgets.QPushButton(self.centralwidget)
        self.tittle_window.setGeometry(QtCore.QRect(320, 50, 641, 131))
        font = QtGui.QFont()
        font.setFamily("HungHau")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tittle_window.setFont(font)
        self.tittle_window.setTabletTracking(False)
        self.tittle_window.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 20pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.tittle_window.setObjectName("tittle_window")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(50, 700, 111, 41))
        self.back_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgb(236, 82, 51,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #EC5233;\n"
"    background-color: rgb(236, 82, 51,65%);\n"
"    font-weight: bold;\n"
"}")
        self.back_button.setAutoRepeatDelay(300)
        self.back_button.setObjectName("back_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(880, 700, 91, 41))
        self.delete_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255,255,255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgb(177, 196, 229,75%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #b1c4e5;\n"
"    background-color: rgb(177, 196, 229,60%);\n"
"    font-weight: bold;\n"
"}")
        self.delete_button.setAutoRepeatDelay(300)
        self.delete_button.setObjectName("delete_button")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(1000, 700, 111, 41))
        self.update_button.setStyleSheet("QPushButton{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.update_button.setAutoRepeatDelay(300)
        self.update_button.setObjectName("update_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(1140, 700, 91, 41))
        self.add_button.setStyleSheet("QPushButton{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.add_button.setAutoRepeatDelay(300)
        self.add_button.setObjectName("add_button")
        self.datatable = QtWidgets.QTableWidget(self.centralwidget)
        self.datatable.setGeometry(QtCore.QRect(50, 200, 1181, 381))
        self.datatable.setStyleSheet("QTableWidget{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.datatable.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.datatable.setColumnCount(5)
        self.datatable.setObjectName("datatable")
        self.datatable.setRowCount(0)
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.background.setMinimumSize(QtCore.QSize(1200, 650))
        self.background.setMouseTracking(False)
        self.background.setTabletTracking(False)
        self.background.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background_fillter = QtWidgets.QLabel(self.centralwidget)
        self.background_fillter.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.background_fillter.setMinimumSize(QtCore.QSize(1280, 800))
        self.background_fillter.setMaximumSize(QtCore.QSize(1280, 800))
        self.background_fillter.setMouseTracking(False)
        self.background_fillter.setTabletTracking(False)
        self.background_fillter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background_fillter.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background_fillter.setAutoFillBackground(False)
        self.background_fillter.setStyleSheet("QLabel{\n"
"    background: rgb(8, 78, 142,60%);\n"
"}")
        self.background_fillter.setText("")
        self.background_fillter.setObjectName("background_fillter")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(190, 700, 111, 41))
        self.logout_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.logout_button.setAutoRepeatDelay(300)
        self.logout_button.setObjectName("logout_button")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setGeometry(QtCore.QRect(330, 700, 511, 41))
        self.search_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.search_input.setText("")
        self.search_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.search_input.setCursorPosition(0)
        self.search_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_input.setObjectName("search_input")
        self.fullname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.fullname_input.setGeometry(QtCore.QRect(150, 630, 351, 41))
        self.fullname_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.fullname_input.setText("")
        self.fullname_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fullname_input.setCursorPosition(0)
        self.fullname_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fullname_input.setObjectName("fullname_input")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(880, 630, 221, 41))
        self.password_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.password_input.setCursorPosition(0)
        self.password_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password_input.setObjectName("password_input")
        self.account_input = QtWidgets.QLineEdit(self.centralwidget)
        self.account_input.setGeometry(QtCore.QRect(520, 630, 341, 41))
        self.account_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.account_input.setText("")
        self.account_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.account_input.setCursorPosition(0)
        self.account_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.account_input.setObjectName("account_input")
        self.id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.id_input.setEnabled(False)
        self.id_input.setGeometry(QtCore.QRect(50, 630, 81, 41))
        self.id_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.id_input.setText("")
        self.id_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.id_input.setCursorPosition(0)
        self.id_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.id_input.setObjectName("id_input")
        self.role_input = QtWidgets.QLineEdit(self.centralwidget)
        self.role_input.setGeometry(QtCore.QRect(1120, 630, 111, 41))
        self.role_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.role_input.setText("")
        self.role_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.role_input.setCursorPosition(0)
        self.role_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.role_input.setObjectName("role_input")
        self.background.raise_()
        self.background_fillter.raise_()
        self.logo.raise_()
        self.tittle_window.raise_()
        self.back_button.raise_()
        self.delete_button.raise_()
        self.update_button.raise_()
        self.add_button.raise_()
        self.datatable.raise_()
        self.logout_button.raise_()
        self.search_input.raise_()
        self.fullname_input.raise_()
        self.password_input.raise_()
        self.account_input.raise_()
        self.id_input.raise_()
        self.role_input.raise_()
        createadmin_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(createadmin_window)
        QtCore.QMetaObject.connectSlotsByName(createadmin_window)
        createadmin_window.setTabOrder(self.fullname_input, self.account_input)
        createadmin_window.setTabOrder(self.account_input, self.password_input)
        createadmin_window.setTabOrder(self.password_input, self.search_input)
        createadmin_window.setTabOrder(self.search_input, self.delete_button)
        createadmin_window.setTabOrder(self.delete_button, self.update_button)
        createadmin_window.setTabOrder(self.update_button, self.add_button)
        createadmin_window.setTabOrder(self.add_button, self.back_button)
        createadmin_window.setTabOrder(self.back_button, self.logout_button)
        createadmin_window.setTabOrder(self.logout_button, self.datatable)
        createadmin_window.setTabOrder(self.datatable, self.tittle_window)

    def retranslateUi(self, createadmin_window):
        _translate = QtCore.QCoreApplication.translate
        createadmin_window.setWindowTitle(_translate("createadmin_window", "BẢNG QUẢN LÝ TÀI KHOẢN QUẢN TRỊ VIÊN"))
        self.tittle_window.setText(_translate("createadmin_window", "QUẢN LÝ TÀI KHOẢN QUẢN TRỊ VIÊN"))
        self.back_button.setText(_translate("createadmin_window", "Quay lại"))
        self.delete_button.setText(_translate("createadmin_window", "Xóa"))
        self.update_button.setText(_translate("createadmin_window", "Cập Nhật"))
        self.add_button.setText(_translate("createadmin_window", "Thêm"))
        self.logout_button.setText(_translate("createadmin_window", "Đăng Xuất"))
        self.search_input.setPlaceholderText(_translate("createadmin_window", "   Tìm kiếm"))
        self.fullname_input.setPlaceholderText(_translate("createadmin_window", "   Họ và Tên"))
        self.password_input.setPlaceholderText(_translate("createadmin_window", "   Mật khẩu"))
        self.account_input.setPlaceholderText(_translate("createadmin_window", "   Tài khoản"))
        self.id_input.setPlaceholderText(_translate("createadmin_window", "   Mã"))
        self.role_input.setPlaceholderText(_translate("createadmin_window", "   Vai trò"))
