# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window4_datatable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datatable_window(object):
    def setupUi(self, datatable_window):
        datatable_window.setObjectName("datatable_window")
        datatable_window.resize(1280, 800)
        datatable_window.setMinimumSize(QtCore.QSize(1280, 800))
        datatable_window.setMaximumSize(QtCore.QSize(1280, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        datatable_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(datatable_window)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(40, 20, 271, 141))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.tittle_window = QtWidgets.QPushButton(self.centralwidget)
        self.tittle_window.setGeometry(QtCore.QRect(370, 50, 501, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tittle_window.setFont(font)
        self.tittle_window.setTabletTracking(False)
        self.tittle_window.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Tahoma\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 16pt \"Tahoma\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.tittle_window.setObjectName("tittle_window")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(40, 680, 91, 41))
        self.back_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgb(236, 82, 51,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #EC5233;\n"
"    background-color: rgb(236, 82, 51,65%);\n"
"    font-weight: bold;\n"
"}")
        self.back_button.setAutoRepeatDelay(300)
        self.back_button.setObjectName("back_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(870, 680, 101, 41))
        self.delete_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255,255,255);\n"
"    font: 75 14pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgb(177, 196, 229,75%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 16pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #b1c4e5;\n"
"    background-color: rgb(177, 196, 229,60%);\n"
"    font-weight: bold;\n"
"}")
        self.delete_button.setAutoRepeatDelay(300)
        self.delete_button.setObjectName("delete_button")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(1000, 680, 101, 41))
        self.update_button.setStyleSheet("QPushButton{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.update_button.setAutoRepeatDelay(300)
        self.update_button.setObjectName("update_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(1130, 680, 101, 41))
        self.add_button.setStyleSheet("QPushButton{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.add_button.setAutoRepeatDelay(300)
        self.add_button.setObjectName("add_button")
        self.datatable = QtWidgets.QTableWidget(self.centralwidget)
        self.datatable.setGeometry(QtCore.QRect(40, 180, 1191, 381))
        self.datatable.setStyleSheet("QTableWidget{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.datatable.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.datatable.setColumnCount(4)
        self.datatable.setObjectName("datatable")
        self.datatable.setRowCount(0)
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.background.setMinimumSize(QtCore.QSize(1280, 800))
        self.background.setMaximumSize(QtCore.QSize(1280, 800))
        self.background.setMouseTracking(False)
        self.background.setTabletTracking(False)
        self.background.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background_fillter = QtWidgets.QLabel(self.centralwidget)
        self.background_fillter.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.background_fillter.setMinimumSize(QtCore.QSize(1280, 800))
        self.background_fillter.setMaximumSize(QtCore.QSize(1280, 800))
        self.background_fillter.setMouseTracking(False)
        self.background_fillter.setTabletTracking(False)
        self.background_fillter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background_fillter.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background_fillter.setAutoFillBackground(False)
        self.background_fillter.setStyleSheet("QLabel{\n"
"    background: rgb(8, 78, 142,60%);\n"
"}")
        self.background_fillter.setText("")
        self.background_fillter.setObjectName("background_fillter")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(150, 680, 111, 41))
        self.logout_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.logout_button.setAutoRepeatDelay(300)
        self.logout_button.setObjectName("logout_button")
        self.idkeyword_input = QtWidgets.QLineEdit(self.centralwidget)
        self.idkeyword_input.setGeometry(QtCore.QRect(40, 610, 141, 41))
        self.idkeyword_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.idkeyword_input.setText("")
        self.idkeyword_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.idkeyword_input.setCursorPosition(0)
        self.idkeyword_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.idkeyword_input.setObjectName("idkeyword_input")
        self.question_input = QtWidgets.QLineEdit(self.centralwidget)
        self.question_input.setGeometry(QtCore.QRect(210, 610, 421, 41))
        self.question_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.question_input.setText("")
        self.question_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question_input.setCursorPosition(0)
        self.question_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question_input.setObjectName("question_input")
        self.answer_input = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_input.setGeometry(QtCore.QRect(660, 610, 571, 41))
        self.answer_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.answer_input.setText("")
        self.answer_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.answer_input.setCursorPosition(0)
        self.answer_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.answer_input.setObjectName("answer_input")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setGeometry(QtCore.QRect(280, 680, 541, 41))
        self.search_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.search_input.setText("")
        self.search_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.search_input.setCursorPosition(0)
        self.search_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_input.setObjectName("search_input")
        self.choosetable_box = QtWidgets.QComboBox(self.centralwidget)
        self.choosetable_box.setGeometry(QtCore.QRect(940, 80, 291, 41))
        self.choosetable_box.setStyleSheet("QComboBox{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    font: 75 14pt \"Tahoma\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.choosetable_box.setObjectName("choosetable_box")
        self.choosetable_box.addItem("")
        self.choosetable_box.addItem("")
        self.choosetable_box.addItem("")
        self.choosetable_box.addItem("")
        self.add_button_ctl = QtWidgets.QPushButton(self.centralwidget)
        self.add_button_ctl.setGeometry(QtCore.QRect(1000, 740, 231, 41))
        self.add_button_ctl.setStyleSheet("QPushButton{\n"
"    font: 75 10pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"Tahoma\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.add_button_ctl.setAutoRepeatDelay(300)
        self.add_button_ctl.setObjectName("add_button_ctl")
        self.background.raise_()
        self.background_fillter.raise_()
        self.logo.raise_()
        self.tittle_window.raise_()
        self.back_button.raise_()
        self.delete_button.raise_()
        self.update_button.raise_()
        self.add_button.raise_()
        self.datatable.raise_()
        self.logout_button.raise_()
        self.idkeyword_input.raise_()
        self.question_input.raise_()
        self.answer_input.raise_()
        self.search_input.raise_()
        self.choosetable_box.raise_()
        self.add_button_ctl.raise_()
        datatable_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(datatable_window)
        QtCore.QMetaObject.connectSlotsByName(datatable_window)

    def retranslateUi(self, datatable_window):
        _translate = QtCore.QCoreApplication.translate
        datatable_window.setWindowTitle(_translate("datatable_window", "BẢNG DỮ LIỆU TƯ VẤN"))
        self.tittle_window.setText(_translate("datatable_window", "BẢNG DỮ LIỆU TƯ VẤN"))
        self.back_button.setText(_translate("datatable_window", "Quay lại"))
        self.delete_button.setText(_translate("datatable_window", "Xóa"))
        self.update_button.setText(_translate("datatable_window", "Cập Nhật"))
        self.add_button.setText(_translate("datatable_window", "Thêm"))
        self.logout_button.setText(_translate("datatable_window", "Đăng Xuất"))
        self.idkeyword_input.setPlaceholderText(_translate("datatable_window", "   Mã Câu Hỏi"))
        self.question_input.setPlaceholderText(_translate("datatable_window", "   Câu Hỏi"))
        self.answer_input.setPlaceholderText(_translate("datatable_window", "   Câu Trả Lời"))
        self.search_input.setPlaceholderText(_translate("datatable_window", "   Tìm kiếm"))
        self.choosetable_box.setItemText(0, _translate("datatable_window", "Tư vấn chung"))
        self.choosetable_box.setItemText(1, _translate("datatable_window", "Công nghệ thông tin"))
        self.choosetable_box.setItemText(2, _translate("datatable_window", "Du lịch"))
        self.choosetable_box.setItemText(3, _translate("datatable_window", "Quản Trị Kinh Doanh"))
        self.add_button_ctl.setText(_translate("datatable_window", "Thêm Câu Trả Lời"))
